### ISSUE TITLE
release/0.1.0 - Loaders

### ISSUE THREAD

**Issue by BenoitSafari** [horameus/Lupokedex#10]
# Loaders
Creer un composant _Loader_ et _PageLoader_.

## Criteres d'acceptation
- [ ] Le composant _PageLoader_ est intégré à Storybook
- [ ] Le composant _Loader_ est intégré à Storybook
- [ ] Le composant _LupoButton_ comporte une props "loading" rendant le _Loader_ a la place du _children_

## PageLoader
_PageLoader_ doit prendre tout l'espace disponible dans l'element html dans lequel il est placé. Le Loader est centré verticalement et horizontalement dans ce composant.

La couleur est parametrable via les props => couleur primaire ou texte

Ci-dessous le loader a integrer
### HTML
```html
<div className="LupoLoader">
    <div className="LupoLoader--circle">
        <div className="LupoLoader--circle--inner"></div>
    </div>
    <div className="LupoLoader--circle">
        <div className="LupoLoader--circle--inner"></div>
    </div>
</div>
```
### CSS
```css
.LupoLoader {
    --size: 5rem;

    width: var(--size);
    height: var(--size);
    border-radius: 50%;
    overflow: hidden;

    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-between;

    transform: rotate(-15deg);
    animation: lupo-loader-roll 0.8s ease infinite;

    & .LupoLoader--circle {
        position: relative;
        width: 100%;
        height: 100%;
        overflow: hidden;
        height: calc(var(--size) / 2.25);
    }

    & :nth-of-type(1) .LupoLoader--circle--inner {
        top: 105%;
        bottom: 105%;
    }

    & :nth-of-type(2) .LupoLoader--circle--inner {
        top: -5%;
        bottom: -5%;
    }

    & .LupoLoader--circle--inner {
        position: absolute;
        border-radius: 50%;
        left: 50%;
        right: 50%;
        transform: translate(-50%, -50%);
        width: calc(var(--size) / 3.1175);
        height: calc(var(--size) / 3.5);
        box-shadow: 0 0 0 9999px var(--palette-text);
    }
}

@keyframes lupo-loader-roll {
    0% {
        transform: rotate(-15deg);
    }
    100% {
        transform: rotate(345deg);
    }
}
```
